### ISSUE TITLE
Blank screen in IE11

### ISSUE THREAD

**Issue by nicolas-despres** [damienleroux/react-grid-layout-builder#2]
Thank you for the great project!
I tried opening your [demo ](http://damienleroux.github.io/react-grid-layout-builder/demo/)with IE11 but I got a blank screen.

Error log:
`SCRIPT438: L’objet ne gère pas la propriété ou la méthode « assign »`
`Fichier : connectReactGridLayoutBuilder.js, ligne : 42, colonne : 3`
Thank you and best regards
Nicolas

**Comment by damienleroux** [comment]
It should be fixed: https://github.com/damienleroux/react-grid-layout-builder/commit/aa1d20c73c9b3db5451b40953b5e05608d09421c, update to 0.0.6

Thank you for sharing

**Comment by nicolas-despres** [comment]
That was fast! Big **merci**
